// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package haos

import (
	"time"
)

type HaosEntityState struct {
	Attributes struct {
		AutoUpdate        bool        `json:"auto_update"`
		DisplayPrecision  float64     `json:"display_precision"`
		EntityPicture     string      `json:"entity_picture"`
		FriendlyName      string      `json:"friendly_name"`
		InProgress        bool        `json:"in_progress"`
		InstalledVersion  string      `json:"installed_version"`
		LatestVersion     string      `json:"latest_version"`
		ReleaseSummary    interface{} `json:"release_summary"`
		ReleaseURL        string      `json:"release_url"`
		SkippedVersion    interface{} `json:"skipped_version"`
		SupportedFeatures float64     `json:"supported_features"`
		Title             string      `json:"title"`
		UpdatePercentage  interface{} `json:"update_percentage"`
	} `json:"attributes"`
	Context struct {
		ID       string      `json:"id"`
		ParentID interface{} `json:"parent_id"`
		UserID   interface{} `json:"user_id"`
	} `json:"context"`
	EntityID     string    `json:"entity_id"`
	LastChanged  time.Time `json:"last_changed"`
	LastReported time.Time `json:"last_reported"`
	LastUpdated  time.Time `json:"last_updated"`
	State        string    `json:"state"`
}
